#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="synapse"
prepare_service 10-synapse

check_container_initialized
check_service_initialized init

liftoff

print_start "Starting Synapse (cat /var/run/synapse/verrsion)"

exec s6-setuidgid synapse synctl --no-daemonize \
                                            start \
                                            ${CONFIG_PATH}

